name: pipeline
dependencies:
  - python=3.8
  - tensorflow=2.7
  - numpy=1.19
  - pandas
  - scikit-learn
  - tqdm
  - matplotlib
  - pip
  - pip:
    - kerasgen==0.1.2
    - tensorflow-addons==0.16.1