name: pipeline
channels:
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pip:
    - imgaug
    # Yolov5
    - pandas
    - pyyaml
    - requests
    - seaborn
    - torch
    - torchvision
    - tqdm
    # ReID
    - kerasgen==0.1.2
    - tensorflow==2.7
    - tensorflow-addons==0.16.1